name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          #- windows-msvc

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          #- toolchain: windows-msvc
          #  os: windows-latest
          #  compiler: msvc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: true

    - name: Setup Boost
      run: |
        echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        LIBRARY=${GITHUB_REPOSITORY#*/}
        echo LIBRARY: $LIBRARY
        echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
        echo GITHUB_BASE_REF: $GITHUB_BASE_REF
        echo GITHUB_REF: $GITHUB_REF
        REF=${GITHUB_BASE_REF:-$GITHUB_REF}
        REF=${REF#refs/heads/}
        echo REF: $REF
        BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
        echo BOOST_BRANCH: $BOOST_BRANCH
        cd ..
        git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
        cd boost-root
        cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
        git submodule update --init tools/boostdep
        python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
        ./bootstrap.sh
        ./b2 -d0 headers

    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DBOOST_ROOT=$BOOST_ROOT_1_72_0

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build

    - name: Test
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest -C ${{ matrix.configuration }}