name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          #- windows-msvc

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          #- toolchain: windows-msvc
          #  os: windows-latest
          #  compiler: msvc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: true

    - name: Cache boost
      uses: actions/cache@v2
      with:
        path: |
          boost_1_72_0
        key: ${{ hashFiles('CMakeLists.txt') }}

    - name: Setup Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2 && tar --bzip2 -xf boost_1_72_0.tar.bz2 && cd boost_1_72_0 && mkdir build-dir && ./bootstrap.sh --prefix=./build-dir && ./b2 install

    - name: Setting Env
      run: |
        echo "${HOME}/.local/bin" >> ${HOME}/boost_1_72_0

#    - name: Setting Env
#      env: 
#        BOOST_ROOT: "/usr/local/src/boost_1_45_0"
#        Boost_LIBRARY_DIRS: "/usr/local/lib"
#        BOOST_INCLUDEDIR: "/usr/local/src/boost_1_45_0"
        
    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build

    - name: Test
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest -C ${{ matrix.configuration }}